### ISSUE TITLE
HTTP basic Authentication is not supported

### ISSUE THREAD

**Issue by kvaps** [kee-org/browser-addon#106]

**Comment by ceres-c** [comment]
It actually is supported, I get a popup with available entries before firefox's builtin form to be filled with user and password

**Comment by codingdrache** [comment]
I had a problem with an entry that matches an exact URL. KeeFox 1.7.2 did not require the forward slash at the end of the URL, but Kee 2.0 does. Now that I corrected the URL, it works as expected.

**Comment by kvaps** [comment]
Not working for me,
I have http authenctification on https://example.org/subdir/

I have keepass record like:
```Title: Some site
login: kvaps
password: hackme
URL: https://example.org/subdir/
Decription: Something there
```
I have tried for remove slash in record, it's not helps too.

**Comment by luckyrat** [comment]
Hi,

Thanks for the interest in helping Kee improve.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable.

Thanks,
Chris

**Comment by Bluejanis** [comment]
I had assumed this function does not work, because I wanted to save the login credentials after logging in to a http basic auth page. The button that allows to save the credentials does not show. Is that normal behaviour that you cannot save basic auth through kee?

I will to try to put the entry manually and see if it works to use it.

**Comment by luckyrat** [comment]
@Bluejanis see #15
