### ISSUE TITLE
Consider entries in keepass without a URL when updating existing entry

### ISSUE THREAD

**Issue by thomaseizinger** [kee-org/browser-addon#107]
I have a lot of "legacy" entries in my keepass database that don't have a URL assigned. Kee therefore does not find them when I visit the site. That is ok, I don't expect it to do so.

However, what is really cumbersome is that when I login to the site manually and choose 'Save latest login', the entry I just copied the password from does not show up in "existing entries". I have to create a new entry and later delete the old one. It would be really great if Kee could just search the database for all entries that match the hostname of the current site or something like that. This would allow me step by step assign URLs to all my legacy keepass entries.

**Comment by luckyrat** [comment]
Hi,

Thanks for the interest in helping Kee improve.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable.

Thanks,
Chris
