### ISSUE TITLE
[Request] Show domain in add login window

### ISSUE THREAD

**Issue by Symbai** [kee-org/browser-addon#109]
As of now in Kee 2.0.0.25 if I select the "Save last login" menu button it shows me a popup box where to save the login but it doesn't show me anywhere for which domain this login is about.
This should be easy to add I guess...

**Comment by luckyrat** [comment]
Hi,

Thanks for the interest in helping Kee improve.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable.

Thanks,
Chris
