### ISSUE TITLE
Credentials not showing

### ISSUE THREAD

**Issue by adaur** [kee-org/browser-addon#112]
Sometimes, either there is a very long delay before the credentials are being shown or they are not at all.

Surprisingly, it still detects the credentials available (notice the "4").
![2017-11-27_145156](https://user-images.githubusercontent.com/959078/33286219-c9cea78a-d382-11e7-80d3-8192eccb9790.png)

**Comment by carlu93** [comment]
I'm having the same issue sometimes. I have to refresh the page to get the credentials shown!

**Comment by luckyrat** [comment]
Hi,

Thanks for the interest in helping Kee improve.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable.

Thanks,
Chris
