### ISSUE TITLE
Missing details

### ISSUE THREAD

**Issue by oregszun** [kee-org/browser-addon#113]
The new plugin does not show the login details (especially url) in the match window only realm and username. Thus making difficult to choose the correct credentials for http basic auth.

The old keefox showed the matched URL as well. Would be nice to see the URL as well.

![image](https://user-images.githubusercontent.com/7438898/33310869-58843bca-d423-11e7-9ae9-828eb15c1f9c.png)

**Comment by luckyrat** [comment]
Hi,

Thanks for the interest in helping Kee improve.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable.

Thanks,
Chris
