### ISSUE TITLE
Error with KeeAutoExec Plugin

### ISSUE THREAD

**Issue by damianetienne** [kee-org/browser-addon#116]
Hello.

I have an issue with the mentioned plugin (KeeAutoExec). This plugin opens multiple databases at once.

Now, with the lastes version of Kee i have the issue that, if i use AutoExec, Kee can´t connect with my databases. I have to open the databases manually one by one in order to Kee to recognize my Keepass instalation and establish conection with the databases.

**Comment by damianetienne** [comment]
Additionaly (if not related with this). If I open 3 databases or more, Kee can't recover password of any of the databases.

**Comment by luckyrat** [comment]
Hi,

Thanks for the interest in helping Kee improve.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable.

Thanks,
Chris
