### ISSUE TITLE
Kee is slow to notice KeePass availability

### ISSUE THREAD

**Issue by mpartel** [kee-org/browser-addon#117]
On Ubuntu 16.04 with Firefox 57, Kee takes what sometimes feels like half a minute to notice that I've opened KeePass. During that time, the icon stays as:
![image](https://user-images.githubusercontent.com/328952/33517032-3d678cec-d785-11e7-9857-601241e44f4d.png)
and I've not found any way of prodding it along.

If Kee is polling for KeePass, would it be reasonable to increase the polling frequency to e.g. every 2 seconds?
Alternatively (or additionally), could Kee poll for KeePass on every page (re)load?

**Comment by lucascosti** [comment]
I've noticed this delay in both Windows and Fedora, too. Windows is on Firefox 57 and Fedora is still using Firefox 56.

**Comment by luckyrat** [comment]
Hi,

It's possible that Kee is having to fall back to a slower polling frequency if a firewall is causing problems with HTTP requests to localhost:12546. The Firefox WebSockets implementation prevents more frequent polling using the more reliable "fallback" method.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable.

Thanks,
Chris

**Comment by ildar** [comment]
One more possible solution: if a user clicks on the OFF then Kee's dropdown menu appears. Is it possible to force-poll on this action? That feels UX-right to me.

**Comment by tux3** [comment]
The underlying issue seems to have been described here: https://github.com/kee-org/KeeFox/issues/189

While the lack of a proper fix is annoying, setting "network.websocket.delay-failed-reconnects" to false in about:config seems to workaround the issue.
