### ISSUE TITLE
Autofilling wrong field - Trello

### ISSUE THREAD

**Issue by asteres** [kee-org/browser-addon#118]
Kee is autofilling the "add to list" field in Trello which is not used for login. Here's the HTML of the field
`<input class="list-name-input" name="name" placeholder="Add a list…" autocomplete="off" dir="auto" maxlength="512" style="cursor: pointer;" type="text">`

**Comment by funkytraffic** [comment]
In my case KF opens a suggestion popup when I click a field, but stops this nerving behaviour when I remove "name" from the textfield name whitelist, even though the target fields donnot have that name "name".

**Comment by luckyrat** [comment]
Hi,

Thanks for the interest in helping Kee improve.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable.

Thanks,
Chris
