### ISSUE TITLE
[Request] Disable Log-Output completely

### ISSUE THREAD

**Issue by dschoeni** [kee-org/browser-addon#120]
Hi! 

Thanks for this great addon. I wondered though, why not giving people an option to disable the log output completely? I'm not very fond of the "Logging system initialised at..." messages in my console, as I use it heavily during development. Any reasons this isn't an option yet?

**Comment by luckyrat** [comment]
Hi,

Thanks for the interest in helping Kee improve.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue unless you want to explain that I've made a mistake but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable. I think that https://forum.kee.pm/t/turn-off-console-logging/283 is relevant.

Thanks,
Chris
