### ISSUE TITLE
http basic auth - re select correct credentials

### ISSUE THREAD

**Issue by oregszun** [kee-org/browser-addon#123]
Hi,

when choosing a wrong credentials at basic auth popup window and posting the data, the popup window will re opened to ask correct credentials. For the second(third, etc/) popup Kee does not offer any credentials, and also cannot use the kee icon as the popup is modal/focused.

**Comment by luckyrat** [comment]
Hi,

Thanks for the interest in helping Kee improve.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable.

Thanks,
Chris
