### ISSUE TITLE
Multiple form, autocomplete

### ISSUE THREAD

**Issue by Poil** [kee-org/browser-addon#124]
Hi,

With latest version of Keefox (on ffx 57), Keefox fill and submit the wrong form on GitLab.

![GitLab Form](http://www.quake.fr/tmp/gitlab.png)

Here it fills the Standard Form (hidden) and not the current displayed one (OPS)

Best regards,

**Comment by luckyrat** [comment]
Hi,

Thanks for the interest in helping Kee improve.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable.

Thanks,
Chris
