### ISSUE TITLE
Kee support for Android

### ISSUE THREAD

**Issue by mildgrim** [kee-org/browser-addon#126]
Are there any plans for adding Android support to Kee? There are a few KeePass implemenations on Android but they aren't very usable for browsing and I refuse to store my passwords in the browser built in password stores which ultimately leads to not being able to use many sites on my mobile device.

**Comment by Sanaki** [comment]
Keepass2Android beta has support for oreo's autofill API now, so you're aware. Granted, that won't help you if you're not on Oreo. I'd imagine the issue with Kee on android is that it relies on a standard interface with keepass, and all versions of keepass on android are third party implementations without that standard interface present.

**Comment by luckyrat** [comment]
Hi,

This would require an Android implementation of KeePassRPC and probably further expansion of Firefox WebExtensions support on Android. Never say never, but it's a large project that I have no intention to focus on in the medium term.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable.

Thanks,
Chris
