### ISSUE TITLE
Kee icons in login form hidden by other element

### ISSUE THREAD

**Issue by ElDani82** [kee-org/browser-addon#127]
I know this is rare, but some websites add their own icons to login forms which are then placed over the one from the Kee extension. One such example I use regularly is the [openmailbox web-mail login](https://app.openmailbox.org/login) page where it's pretty difficult to position the cursor in a way that opens the Kee matched logins popup.

Instead of mis-clicking all the time, I've taken to use 'matched login entries' from the toolbar popup but it's less comfortable than the awesome inline method that was introduced with the move to WebExtensions. This wouldn't even be a big issue, but the form isn't auto-filled by the extension like almost all others are.

Is there a simple and easy way to either auto-fill the form or to display the Kee icon on top or at a different offset? I'd take a short-cut I could use to open the list of matched login entries too.

**Comment by luckyrat** [comment]
Thanks for the feedback and the example page.

I've recently added information about this problem to the troubleshooting guide on the forum.

https://forum.kee.pm/t/troubleshooting/560#heading--kee-icon-field-broken

There's no way to make the Kee icon always appear on top - web browsers just don't give browser extensions that ability; and offsets would lead to a world of pain and chasing around outdated configurations (and what happens when other browser extensions get involved too? - #195 ) - I'm afraid the main menu button, keyboard shortcut or context menu features will have to suffice when conflicts with other elements appear. As you say, it is thankfully still a relatively rare event at the moment.

Please use the forum to continue discussion if necessary.
