### ISSUE TITLE
Memory Leak in Firefox Addon

### ISSUE THREAD

**Issue by SpiderManAPV** [kee-org/browser-addon#128]
Unfortunately I didn't manage to get any screenshots or anything like that, as I didn't think to write this comment until after I closed Firefox.  I'm pretty positive the Firefox addon has a memory leak, however.  When using Firefox yesterday I noticed it taking an abnormal amount of memory, but didn't think anything of it as I had a large number of tabs open.  I put my computer into sleep and closed most of my tabs last night.  Today when I went to use Firefox it was running extremely slow.  I opened up task manager and Firefox was using over 5,500MB of memory.  When I alt-tabbed back to Firefox there was a pop-up saying that the "Kee" extension was slowing Firefox down and asking if I'd like to disable it to attempt to speed up the browser.  I declined, opened Firefox back up, and it's back down to 1,300-1,600MB of memory as opposed to the 5,500MB despite opening up more tabs.

**Comment by SpiderManAPV** [comment]
Just as an update, I've left Firefox open for a while with just a few tabs open.  It's been growing in memory usage until, as of this posting, it's at 2,690MB.  Is there anything I can do to help diagnose the issue?

**Comment by luckyrat** [comment]
Hi,

Thanks for the interest in helping Kee improve.

I don't see any problems with memory usage on my system with Kee enabled so hopefully if there is a problem with it, we can identify a workaround. Note that the last time I checked, those Firefox addon "slowing down" warnings were bogus (and unrelated to memory consumption); that situation may well have been improved in recent months but it would require deeper investigation to find out if the warning is worth worrying about.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do put the latest info you have about this issue onto https://forum.kee.pm/t/issue-memory-leak-in-firefox-addon/512.

Thanks,
Chris
