### ISSUE TITLE
Possible issue will auto filling forms

### ISSUE THREAD

**Issue by jdunn0** [kee-org/browser-addon#129]
There is a story I found via the Firefox subreddit titled [Ad targeters are pulling data from your browser’s password manager](https://www.reddit.com/r/firefox/comments/7n4jas/ad_targeters_are_pulling_data_from_your_browsers/) which mentions ad tracking scripts that include hidden forms in web sites and then uses Javascript to grab user names that are auto filled in by a password manager.
I'm curious if this issue can happen when using Firefox with the Kee extension.

**Comment by Sanaki** [comment]
By that description, any password manager that autofills without requiring any user triggered input will be susceptible, Kee included.

**Comment by dayvan** [comment]
I wonder what could be a possible solution for this?

The autofill mechanism (whether built in the browser or Kee) could check if the login fields are actually visible to the user (check html and css)? or can that also be circumvented?

**Comment by Sanaki** [comment]
Simple checks are easy enough. If the field has visibility=hidden on it, don't autofill, things like that. Kee may already do that much. When javascript gets involved though, it's not necessarily that simple, and the more checks Kee does, the slower it runs overall. That translates into overall browser slowdown, which is obviously a problem.

That all concerns default behavior of course. From the standpoint of a concerned user, the easiest solution is to change "When Kee chooses a matching login for a standard form" to "do nothing" and only autofill by manual selection. That's not optimal of course, but it's the only surefire solution (assuming otherwise diligent web usage).

**Comment by Cronycs** [comment]
There is a demo of this abuse here : https://senglehardt.com/demo/no_boundaries/loginmanager/sniff.html
I just tried and as mentioned by Sanaki, Kee is vulnerable as any password manager that autofill.

**Comment by luckyrat** [comment]
Hi,

Thanks for the link.

Kee has always offered the option to disable auto-fill to act as mitigation for issues where the website can't be trusted to remain secure from one visit to the next (or as in this case, from one page to the next).

If a website owner allows a malicious script onto their website with same-origin permissions, there is nothing that can be done to protect the data that a user submits to that site. Sure, there are mitigations that can be applied but a determined personal data collector (advertiser) can take an unlimited number of workarounds for those mitigations (probably resulting eventually in an arms-race comparable to anti-virus signature updates on desktop PCs). Whether someone (and who) should invest effort to protect users from this risk is a big and interesting topic but ultimately tangential to password managers.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do get involved in any similar discussion on https://forum.kee.pm or create a new topic there if you want to followup on this discussion.

Thanks,
Chris
