### ISSUE TITLE
Compatibility with KeePassHTTP

### ISSUE THREAD

**Issue by hackel** [kee-org/browser-addon#13]
Since the conversion to a WebExtension is such a major rewrite, perhaps it is appropriate to revisit the question of supporting KeePassHTTP.  For me, the advantage woulld be that I could switch to running KeePassXC instead of the terrible .NET client.  I have not looked into the protocols at all, so I have no idea what advantages KeePassRPC has over KeePassHTTP, but seeing these two APIs unified I believe would be a huge step in the right direction, but for this extension and any others.

**Comment by luckyrat** [comment]
KeeFox 2.0 (WebExtensions) already works with KeePassRPC and won't work with KeePassHTTP - as discussed elsewhere, it's a slightly more technically limited protocol so there are no advantages of switching KeeFox to use that instead of KeePassRPC.

If someone wants to port KeePassRPC to the plugin languages of other KeePass ports I'm always happy to offer help and advice with that endeavour.

**Comment by robsonsobral** [comment]
Is [keepassxc-browser](https://github.com/keepassxreboot/keepassxc-browser) a better alternative to KeePassHTTP? KeePass is awful to run on MacOS, while KeePassXC run really well.

Thank you.
