### ISSUE TITLE
Kee-Icon appears on way too many form fields

### ISSUE THREAD

**Issue by fritzgithub** [kee-org/browser-addon#130]
We run an online-business. I use on our own website and its subdomains maybe 25 logins.
The weird thing is, that for example on our own signup-form, kee puts its icon in every input or textfield:
![kee-icon_in_form_fields](https://user-images.githubusercontent.com/11574060/34486861-16af5e8a-efd2-11e7-8a2c-02ef93562076.PNG)
This ist rather annoying for us, but would be pretty bad if this would happen when our users who also use kee experience the same, when they edit their data (which happens very often).
Help would be great,
thanks,

Fritz

**Comment by Stuzz** [comment]
Another example of this happening (atleast for me) is the page number box in the firefox pdf reader.
![afbeelding](https://user-images.githubusercontent.com/4184375/34566469-007aef56-f15f-11e7-8bd7-29d0df51ea42.png)

**Comment by luckyrat** [comment]
Hi,

Thanks for the interest in helping Kee improve.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue unless you want to explain that I've made a mistake but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable. I think that https://forum.kee.pm/t/how-to-configure-the-new-contextual-kee-buttons/278 is relevant.

The issue specific to the PDF page numbers is tracked at https://github.com/kee-org/browser-addon/issues/77

Thanks,
Chris
