### ISSUE TITLE
After saving a new password the database file on disk is not changed

### ISSUE THREAD

**Issue by arty-name** [kee-org/browser-addon#136]
My wife has just noticed that her KeePass database doesn’t contain any passwords added in about two months (roughly coincides with the update to the WebExtension).

Steps to reproduce:

0. Have the newest Kee in the newest Firefox on Windows 10 with all updates, and the KeePass2 and its plugins are also of the latest version and connected to Kee
1. Unlock the database in KeePass2
2. Make sure the setting for KeeFox in KeePass "Save the database file after saving an entry" is checked 
3. Log in to a website and save the password through Kee as a new entry
4. Confirm that the new entry is visible in KeePass and that it doesn’t indicate the database is not saved (there is no asterisk after the file name in the window title)

Expected: the change is saved to the file on disk.

Actual: the change is **not** saved to the file on disk, the change is lost after restart. Clicking "Save" button in the KeeFox actually saves the file on disk. File not being saved and saved are clearly visible through Dropbox file history as well.

Frankly speaking I cannot judge if this issue belongs to Kee, to KeePass, or to any of the intermediate communication plugins. Any thoughts?

**Comment by luckyrat** [comment]
Make sure it's not saving to a conflicted file on DropBox?

I see the expected behaviour on my system so if you're definitely looking at the right file, there must be a configuration difference somewhere or maybe you have some plugins installed other than KeePassRPC. If so, try disabling them to see if there is a conflict with one of them or not.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable with any updated information you can supply.

Thanks,
Chris

**Comment by arty-name** [comment]
Yes, the Dropbox is not the cause of it, it was the first thing I have checked. 

I got the point that this bug should be first discussed on the forum, will do so. Thanks for the quick response! :)
