### ISSUE TITLE
Trigger Change/Input Event after Autofill appears broken

### ISSUE THREAD

**Issue by gadyck** [kee-org/browser-addon#141]
I am having the same problem as described in issue #83  I am unable to use autofill and enter to logon to my Asus router.  Attempting to do so results in an "Invalid user or password" response.

Comparing the keefox 1.7.2 for formsFillTab.js to 2.0 for formFilling.ts, I see that the code is slightly different.  The old code is-
  domElement.dispatchEvent(new content.UIEvent('change', {view: content, bubbles: true, cancelable: true}));
  domElement.dispatchEvent(new content.UIEvent('input', {view: content, bubbles: true, cancelable: true}));
The new code is-
  domElement.dispatchEvent(new UIEvent("input", {view: window, bubbles: true, cancelable: true}));
  domElement.dispatchEvent(new UIEvent("change", {view: window, bubbles: true, cancelable: true}));

I don't know enough to say if this is right or wrong, but I believe something *is* broken with it.

I am unable to provide any diagnostic traces, as enabling trace does not appear to work in this release.

Regards, Greg

**Comment by luckyrat** [comment]
Hi Greg,

I think you may be talking about https://forum.kee.pm/t/kee-is-autosubmitting-some-entries/415/2

The order of the input and change events has been changed to fit with the usual order of those events. It's likely that if any bugs have been caused by that change, many more have been resolved. I'm not aware of any specific cases either way though.

If that link doesn't apply, please feel free to search for other similar issues and post a new topic on the forum. For future reference, per the recently announced [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), this message should be posted in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.
