### ISSUE TITLE
Ongoing KeePassRPC Authorisation in Firefox

### ISSUE THREAD

**Issue by bcutter** [kee-org/browser-addon#142]
Hi,

everytime Kee connects to KeePass I am forced to provide an authorisation key.

First of all: Yes, I´ve read and understood everything posted here:
- https://github.com/kee-org/KeeFox/wiki/en-%7C-Troubleshooting#keepassrpc-authorisation
- https://forum.kee.pm/t/troubleshooting/560#heading--enter-password-every-time

My settings:
- Kee & KeePassRPC security setting set to MEDIUM
- Expiry time set to 2160 hours
- KeePassRPC setting tab "Authorised clients" shows a valid session with expiration time matching expiry time

**Therefore I´m pretty sure Kee can´t (permanently) store the authorisation information.**

Can you please tell me where it´s stored in Firefox? I have a few security addons in Firefox (Disconnect, HTTPS Everywhere, NoScript, PassSec+, Referer Modifier, uBlock Origin), but couldn´t rule them out yet.

**Comment by bcutter** [comment]
**Versions:**
+ Kee: v2.0.0.25
+ KeePass: v2.38
+ KeePassRPC: v1.7.3

Anything else I can provide?

**Comment by luckyrat** [comment]
Per the recently announced [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please post this message in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.

Before you post though, please rule out those other addons, it is more likely than not that one of them is the source of the problem.

**Comment by bcutter** [comment]
I created a new Firefox profile: same result. But I´m gonna create another community account now and will post there... most likely to end up back here anyway.

**Comment by bcutter** [comment]
Update: https://forum.kee.pm/t/ongoing-keepassrpc-authorisation-in-firefox/770
