### ISSUE TITLE
Save Forms without a password field

### ISSUE THREAD

**Issue by donauweb** [kee-org/browser-addon#144]
At the moment only forms that have a password field are saved. But why? There are a lot of forms I use regularly that do not have a password field. I would like to have an easy way to fill them with the same data again and again.

**Comment by luckyrat** [comment]
Per the recently announced [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please post this message in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.

A quick note here though: finding login forms is very different to finding all forms. We are only able to find login forms so successfully by ignoring some other forms.

Such a feature is not likely to be within scope of Kee in the foreseeable future.
