### ISSUE TITLE
Document work required to support MS Edge

### ISSUE THREAD

**Issue by luckyrat** [kee-org/browser-addon#147]
The first step of the project to enable Edge support is to play around with the addon in Edge and explore API documentation to establish which browser APIs are not supported by Edge. We can then create specific issues to address any incompatibilities that are discovered.

However, even this first step is blocked by the following Edge bug which needs to be resolved one way or another before Edge support can even be contemplated: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9421085/

**Comment by danekja** [comment]
Hello, today I tried to port the chrome addon to Edge, with the following findings:

1. With the changes from [this PR](https://github.com/mozilla/webextension-polyfill/pull/114), the mozilla polyfill almost works. Some tweaks are still necessary, but nothing which should prevent main development of the port. 
1. Together with using Edge Extension Toolkit, I got a version which required only few changes to get running.
1. References to `browser.browserAction.set*` which are used to set text and colour of the icon had to be changed to `chrome.browserAction.set*`. My understanding was that maybe the polyfill and wrappers generated by the toolkit were interfering with each other, but I haven't been able to track it down.
1. Colour specification had to be changed into hex form (Edge apparently does not recognize the colour names).
1. Edge does not support commands API.

So far so good, extension can be installed and configured.

### BUT

Edge [does not support](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8984919/) opening websocket connection to localhost. At least not without specifically enabling it from command prompt (I have yet to test that). This is apparently by design and it is not going to change - recommended way is to use [native extensions](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/native-messaging#creating-an-extension-with-native-messaging).

So it seems to me special communication layer would need to be implemented for Edge on both addon and keepass plugin sides. Sounds like a lot of work to me, but im not really acquainted with the technology.

**Comment by danekja** [comment]
### Additional findings
I have been able to run the extension in Edge with the following steps (additional to what is mentioned above):

1. **Enable connection to localhost via websocket** by running `CheckNetIsolation LoopbackExempt -a -n=Microsoft.MicrosoftEdge_8wekyb3d8bbwe` as admin in windows console
1. **Provide polyfill for TextEncoder API**: [Repository](https://github.com/inexorabletash/text-encoding)
1. **Provide polyfill for crypto and JS implementation of SHA-1** Edge does not support SHA-1 natively. [Polyfill](https://github.com/PeculiarVentures/webcrypto-liner), [asmcrypto v0.22.0](https://github.com/asmcrypto/asmcrypto.js/tree/v0.22.0)

#### What works

- connecting and authenticating to KeePass
- searching passwords in db via the extension popup
- copying username and password from the extension popup

#### What does not work (yet)

- generating new passwords (error message probably means incompatibility in code)
- automated password search - the popup behaves as if there were no passwords stored for the page
- automatically filling username and password fields in forms (blocked at least by the previous one)

**Comment by luckyrat** [comment]
This polyfill from AdBlockPlus allegedly enables Edge support. I've not looked into it in detail so I'm not sure to what extent that is true or how close it is to a generic polyfill like the Mozilla one but it'll be worth looking at sometime:

https://github.com/adblockplus/adblockpluschrome/blob/master/polyfill.js

**Comment by luckyrat** [comment]
We're still essentially blocked on external factors here but can be hopeful that at some point in the coming year Microsoft will announce full support for Chrome-compatible addons as part of their new browser, thus either invalidating or at least vastly simplifying this issue. I don't think we should spend any more time on the current version Edge given its short remaining shelf life.

**Comment by danekja** [comment]
Agreed, that is basically the main reason I havent spent any additional time on this since the last post.

**Comment by t-p-tan** [comment]
Hi guys, recently after a few browser benchmarks and reviews it seems Edge is top-to-toe with Chrome, so I decided to give it a test drive. My default has always been Firefox Nightly. (I have 4 surface web browsers on stand-by at all times: Firefox Nightly, Chrome Dev, Brave Dev and Edge Beta)

I come here because the extension is not here, and I learnt a lot reading this issue. I wonder if now is the good time to pick this up again, but I am not familiar with the overall Edge roadmap this year and beyond.

**Comment by luckyrat** [comment]
I'm closing this issue since it sounds as though the extension currently works in Microsoft Edge. If there are any particular problems they can be raised and discussed on the [community forum](https://forum.kee.pm) and we can then potentially open one or more specific issues for implementation on here as required.
