### ISSUE TITLE
REQUEST : KeeFox autofill password field with last generated password

### ISSUE THREAD

**Issue by FataPlex** [kee-org/browser-addon#163]
[Kee 2.2.9]
When signup on a new website with form, KeeFox just let me generate a new password for this website (and put it in KeeFox Generated Password Backups group/folder in the KeePass connected database).
But it doesn't autofill the current form (password field) with it (last generated password). Even if the entry exists in the database !

It would be a great feature if KeeFox could do this !

**Comment by Darksider3** [comment]
It can, actually. You've first to enable the auto-fill for said password in the database.
Go to the entry in KeePass which u just generated and want to use later, change to the "kee"-tab in the edit-interface and uncheck the checkbox with "Hide this entry from Keefox". :)

**Comment by luckyrat** [comment]
Thanks for the tips @Darksider3 and thanks for the suggestion @FataPlex, although it would have been better to raise this in the community forum so that more people can get involved with discussions from a single place.

It's not always obvious what that current form / desired password field(s) is/are so this isn't likely to be a feature we can implement in its own right, although potentially some wider changes to the add-on feature-set could enable something that makes signups faster, which I think is your underlying desire.

I'll close this for now since I don't think it's directly actionable but feel free to post on the forum and continue the discussion there if you want.

**Comment by freMea** [comment]
KeePass | KeePassRPC | Browser | OS 
--------- | ------------- | ---- | ---- 
2.39.1 | 1.8 | Vivaldi 1.15.1147.42 (64 bits) | Windows 10 1607 x64
---

Thanks for the tips @Darksider3.

But I thought Kee was able to copy the generated password to clipboard so the user could just paste it in an input field. For me it doesn't work.

**Comment by kifujin** [comment]
What kind of workflow is expected when creating a password for a site here? Use right clicks in page (or the Kee button) and clicks generate password, then leaves the browser, pulling up KeePass to change a flag on the new entry, and then go back and "find matching logins" to get the entry they just made?

Wouldn't a much cleaner workflow be to be able to generate and fill passwords straight from right clicking the password field (or clicking the Kee icon in the field) and selecting the password algorithm?

Until reading this thread, I had no idea newly generated passwords were placed into the clipboard for manual pasting as it wasn't communicated anywhere I could see.
