### ISSUE TITLE
Increasing amount of fields to be allowed for a fill in

### ISSUE THREAD

**Issue by artgru** [kee-org/browser-addon#167]
Hey there,
I've noticed that in one of the newer version there is a maximum amount of fields (<25) being checked and above this limit Kee won't fill anything.
Sadly in one of my forms where I need to authenticate with additional password fields (not only a pasword but ie. randomly picked numbers from my own ID) Kee refuses to fill up the form due to this limitation.

I was also using Kee for filling up a form for generating my monthly invoices. Is it possible to make a variable amount of fields or at least increase it to a 100 fields?

Debug info "Lost interest in this form after finding too many fields"

**Comment by luckyrat** [comment]
Can you provide a link to this page that requires more than 25 user ID or password components? It almost beggars belief that any website would place such an onerous requirement on their users :-D

As far as large scale form completion for things like invoices is concerned, I'm afraid that's not completely within the scope of Kee and since increasing the number of fields risks serious performance problems on other websites, I wouldn't recommend even an optional increase in this limit for that use case.

The only way that might work is if we set it as a bounded (10-100) site-specific setting but I'm not convinced it's worth the effort (we currently have no support for site-specific settings that cannot be set at the top level for all sites).

**Comment by artgru** [comment]
Hello, it's a bank login: https://www.bankmillennium.pl/osobiste2/LoginSignIn
on the first field type whatever login and get to the 2nd stage.

**Comment by luckyrat** [comment]
Hi,

Thanks for the link. There doesn't seem to be any easy way to enable this form to work within the scope of my concerns above so I'm going to close this for now but we can keep an eye on if there are other websites like this and I'll keep it in mind as a good example of an edge-case in future in case any other changes to Kee might allow us to safely relax the field quantity limitations. Sorry that I can't offer a fix for this site at the moment.

For the record, using "MilleKod" = 123456, I see 11 character password fields, two of which are enabled and the rest disabled. The form is at the top-most level of the page and so encompasses far more than just the visible login form. There are 69 form elements, 32 of which are of type hidden.

By the way, this sort of discussion would be better on the [community forum](https://forum.kee.pm) in future since it's more likely that other users will notice it and it would allow us to gradually work out exactly what changes (if any) to make to Kee before creating a GitHub issue.
