### ISSUE TITLE
Kee doesn't show save last login detail for this page

### ISSUE THREAD

**Issue by dingdingdon** [kee-org/browser-addon#168]
https://online.mbbank.com.vn/retail/EstablishSession

This is the online banking of a Vietnamese banking, when I login, there is no save last login detail from the Kee plugin. 

Thank you

**Comment by ggeorgg** [comment]
I have noticed the same behavior on some online banking websites. Maybe a security mechanism?

**Comment by luckyrat** [comment]
Per the recently announced [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please search and then post this message in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.
