### ISSUE TITLE
Kee icon shows OFF and won't connect to running KeePass

### ISSUE THREAD

**Issue by antimatter84** [kee-org/browser-addon#169]
I have the latest versions of Firefox, Kee, KeePass and the RPC plugin. OS is Windows 7 x64 with latest updates.

Firefox 59.0.1 (64-bit)
Kee Addon 2.3.19.1
KeePass 2.38
KeePass Plugin 1.7.3

The kee icon in the Firefox toolbar shows "OFF" with red background. It won't connect to KeePass. KeePass is running, logged in and its workspace is unlocked. The RPC plugin is loaded.

I also tested the the JSFiddle thingy linked in the troubleshoot pages which says: 

> Keefox / Keepass WebSocket Test
ERROR: undefined
Could not connect to KeepassRPC (This is bad)
DISCONNECTED

I ran keepass.exe with "--debug --KPRPCDebug=kee.log" and this is the log:

>Logger initialised.
Client managers started.
RPC service started.
Starting KPRPCServer
Fleck says: Constructed server at ws://localhost:31001. Explicit port: 8181. Implicit port: 31001. Loopback only? True
Fleck says: Starting server at ws://localhost:31001. Loopback only? True
Fleck says: Server started at ws://localhost:31001
Started KPRPCServer
RPC server started.
KPRPC startup succeeded. 

Is this correct? Should the server open by using port 31001?
I glanced at the code of the Firefox addon and the file "app.js" has this part:

    configureConnectionURIs() { 
        const defaultWebSocketPort = 12546;
        //...
    }

This may be a port mismatch between the addon client and the RPC plugin.

**Comment by luckyrat** [comment]
Per the recently announced [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please search and then post this message in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.
