### ISSUE TITLE
Exclude gitlab.com projects filter input field

### ISSUE THREAD

**Issue by ALEXGREENALEX** [kee-org/browser-addon#172]
Please, add to black and white lists more settings, for example
`type="search"` (must be added to blacklist)
![default](https://user-images.githubusercontent.com/10901025/38293723-3d978808-37f1-11e8-9714-c516d905b140.png)

**Comment by luckyrat** [comment]
Per the recently announced [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please search and then post this message in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.

**Comment by ALEXGREENALEX** [comment]
But this is a bug/issue. KeeFox trying to paste Login("MyMail@example.com" on screenshot above) in search field at gitlab site (just lock at screenshot).
