### ISSUE TITLE
Kee logs "Logging system initialised" multiple times in the Firefox console 

### ISSUE THREAD

**Issue by BoffinbraiN** [kee-org/browser-addon#173]
Using Firefox 59.0.2 (64-bit) and Kee 2.3.19.1, when loading any page, I always get at least one occurrence of this log (INFO) message in the dev console:

```
Logging system initialised at Thu Apr 05 2018 13:00:53 GMT+0100 (GMT Daylight Time)
```

The source of the message comes from the extension's common.js script. My Kee settings have log verbosity set to Warnings. Sadly, Firefox no longer allows us to filter the console to exclude messages created by internal chrome or extension scripts, so I cannot filter these out without hiding all Info messages.

![image](https://user-images.githubusercontent.com/13255058/38365124-06304282-38d3-11e8-87a0-ed3f34c695e4.png)

**Comment by luckyrat** [comment]
Per the recently announced [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please search and then post this message in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.
