### ISSUE TITLE
Don't show duplicate popups for same origin & realm

### ISSUE THREAD

**Issue by Perlover** [kee-org/browser-addon#186]
I have a long time an anoying bug as i think:

Your plugin type: WebExtension

If have **Basic "Auto-login when only one match" off** (i translated to English from Russian because i have Russian-language) and when a some **index page doesn't have basic authorization credentials** but **its elements have ones** (for exaple some ajax requests to URLs with same origin & realm ID) - i have many popups from KeeFox with same basic authorization modal popups. I expect to have only one.

For example `lncli-web` admin tools has same layout, here is work example: https://46.229.165.145:8280/. If you will add to Keepass2 this URL and fake user & password - you will see 5-6 popups! All these popups will have same `origin` & `realm` fields.

Thanks!

**Comment by luckyrat** [comment]
I'm not sure what we could do differently here since every URL could potentially result in different matches from KeePass - they're not guaranteed to be unique by origin and realm. Feel free to discuss further on the [community forum](https://forum.kee.pm) if you have some ideas for improvements though since I can understand why a lot of popups like this would be pretty annoying.
