### ISSUE TITLE
The plugin is incompatible with the current keepass version (Keepass 2.39.1, Kee 1.8.0)

### ISSUE THREAD

**Issue by boldt** [kee-org/browser-addon#188]
I am getting the following issue with Keepass 2.39.1 and the the newest `KeePassRPC.plgx` (SHA-1: `66520bc12d54e6090913c0ea64ffac1daadb71fc`) available at https://github.com/kee-org/keepassrpc/releases (1.8.0):

![bildschirmfoto vom 2018-07-09 11 15 35](https://user-images.githubusercontent.com/750793/42441896-8a79bfd8-8369-11e8-8c6c-18f55d400192.png)

**Comment by kaffeeringe** [comment]
I get this error on Windows 7 with Keepass 2.3.9 on Portable Apps.

**Comment by dlech** [comment]
If you are using windows, then it is a different issue. On Windows it is probably caused by an older version of KeePassRPC. Make sure you don't accidentally have two copies of the plugin installed. Also, run KeePass.exe from the command line with the -debug option to get more information and open a new issue (preferably at https://github.com/kee-org/keepassrpc/issues) if there are still problems.

**Comment by luckyrat** [comment]
Don't forget to search on https://forum.kee.pm for all the other similar issues and solutions if this is still a problem for you.
