### ISSUE TITLE
Can kee match url more strictly?

### ISSUE THREAD

**Issue by ghost** [kee-org/browser-addon#194]
Some website use two diffrent password under one domain,Xfce.org,as example:
bugzilla.xfce.org and forums.xfce.org acounts isn't the same one,but kee show two acounts in either of one,can kee add a option to match URL by full path ,not by domain

**Comment by ggeorgg** [comment]
Do you know those settings in KeePass? 
![grafik](https://user-images.githubusercontent.com/13244552/46402683-becf8a80-c700-11e8-9405-6ce75bab6fd4.png)
I think this it what you are looking for :) Give them a try and play around a bit.

**Comment by FateRover** [comment]
after changing to hostname,nothing chaged,still 2 acount mached while actully there is only one is correct.
by the way ,firefox62 on debian testing /linux

**Comment by luckyrat** [comment]
Per the [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please search and then post messages like this in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.
