### ISSUE TITLE
Kee generated passwords are automatically hidden

### ISSUE THREAD

**Issue by matlink** [kee-org/browser-addon#198]
When I generate a new entry from Firefox using this add-on, the new password is hidden from Kee. I need to edit it in KeePass and untick the "Hide this entry from Kee".
Is there any way to disable that automatic hide?

**Comment by miblo69** [comment]
I have the same issue. How to set the default to *not*  hide the entry?  KeePass 2.39.1, Kee 2.3.19.1

**Comment by luckyrat** [comment]
Per the [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please search and then post messages like this in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.
