### ISSUE TITLE
Proposal: Settings syncronisation over keepass database

### ISSUE THREAD

**Issue by ciborge** [kee-org/browser-addon#209]
Would it be a good idea to use the currently used keepass database to store the settings of Kee ?
Maybe by creating an entry in the database that store every settings in fields that Kee would go and lookup on initial connection.

this would for a better cross browser/cross systems use.

**Comment by luckyrat** [comment]
I've recently [announced Kee Vault](https://forum.kee.pm/t/kee-vault-and-kee-version-3-0/2025), which already includes this idea. It works because Kee Vault has an inherent concept of a "primary" database associated with a person/account, something missing from KeePass. I'll close this issue now since there's nothing more we can do because having multiple databases loaded into KeePass without this "primary" concept would cause conflicts and settings to get lost/reset seemingly at random.

Only settings which are applicable across multiple devices/browsers are synchronised - feel free to discuss on the forum if there are any that you think I've incorrectly categorised as either synchronisable or not and I can refine the list in a future version.

PS: At least at the moment "primary" is also "only" but this feature doesn't depend upon that detail.
