### ISSUE TITLE
https auth of pinned tab

### ISSUE THREAD

**Issue by pcause** [kee-org/browser-addon#21]
I have a pinned tab and the site needs http auth.  When firefox (latest nightly) starts I get the http auth prompt but nothing from keefox.  I noticed that keefox l has the "off" image overlaid on the toobar.  I suspect this is an issue where firefox initialized the addin before it opens the pinned tab.

**Comment by luckyrat** [comment]
Unfortunately, I'm not sure I'm keen on the only potential fix for this. Firefox doesn't allow an add-on to alter the startup behaviour of the browser so even if it is starting add-ons before loading the pinned tabs (unconfirmed) only add-ons which unconditionally block HTTP Auth access could reliably interject when the pinned tab loads.

The only possible approach we could take is (assuming Firefox guarantees Kee will be started before any pinned tab is loaded) is to block all HTTP Auth requests until Kee finishes its startup process (which depends on various other Firefox features so can't complete in a predictable time or order). That's far from trivial for Kee to implement - we'd have to track when the connection to KeePass has been completed (or possibly just wait for a fixed time).

For an average startup that'd be OK but it would get especially difficult if we're indefinitely blocking Firefox requests while waiting for a user to authorise a new connection between Kee and KeePassRPC. I'm sure when speccing out such a feature we'd come up with a dozen other edge cases but all are academic unless Mozilla will confirm that they will allow all add-ons to start before attempting to load pinned tabs so that would have to be the first step to getting this limitation addressed.

**Comment by pcause** [comment]
Here is the *strange* thing - this seems to work on Linux but not on Windows.  it doesn't always work on Linux but seems to most of the time.  Bug in FF???  I haven't tried this on Chrome.  Does it work there?

**Comment by luckyrat** [comment]
It works in Chrome when I try it there. Given the asynchronous nature of modern add-ons like Kee, I wouldn't expect this to be a reliable behaviour although it's possible that one would find noticeable differences across browser implementations and hardware capabilities.

Certainly worth asking the Firefox team if there's something in particular that might make it more likely on Firefox compared to Chrome. Calling it a bug might be a going a bit far but it could be, and certainly could be an implementation detail that they would be willing to adjust in future to increase compatibility with Chrome add-ons. Would you be up for contacting them? I can provide more technical details if/when it reaches that stage but the basic overview and this issue should be enough to give them a starting point for diagnosis.

**Comment by luckyrat** [comment]
Seems unlikely there is anything we can do here - adjustments to this behaviour would be up to Firefox to implement so I'm closing for now at least.
