### ISSUE TITLE
Using entry title to match if URL is empty

### ISSUE THREAD

**Issue by univert** [kee-org/browser-addon#212]
Some legacy entry url might be empty, in such cases can we use the entry title to do matching?

**Comment by luckyrat** [comment]
Per the [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please search and then post messages like this in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.

**Comment by marcovtwout** [comment]
Found a similar discussion in https://forum.kee.pm/t/feature-request-find-entries-without-url-search-and-update-entries/1690/7
