### ISSUE TITLE
DropBox auto submit form not working

### ISSUE THREAD

**Issue by thomaslc66** [kee-org/browser-addon#213]
Hello everybody and thanks for the work you've done on kee. It's a realy good feature to have.

I'm curently using it with chrome and firefox and i've set in kee settings to auto-submit the form, so all the login work is done without my intervention. Working fine on all other site but when i try to log into dropbox account i'm dealing with some kind of error.

To investigate i've disabled the auto-submit settings and what i've noticed is that dropbox.com/login is loading, then my credentials are filled and 2 seconds latter they disappered ?? if i wait, then they reappeared again and i can click on the button to login.

Why is that, for sure it's dropbox website that is reloading some components on the page. But with auto-submit when the login button is clicked dropbox sees no credentials and dispaly an error page. 
Maybe it's possible to increase the delay before submitting the form or i don't know ? maybe you have some other workaround?

Thanks for your response.

Regards

**Comment by luckyrat** [comment]
Per the [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please search and then post messages like this in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.
