### ISSUE TITLE
Can Make This Addon Rread Bookmark so that save bookmarks to keepass

### ISSUE THREAD

**Issue by GoogleBeEvil** [kee-org/browser-addon#215]
AIK,Firefox's bookmark sync system isnt so well and many people backup bookmark manully,can this addon read bookmark json file and convert it to keepass database,so that we can sync bookmark through netdisk

**Comment by luckyrat** [comment]
Per the [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please search and then post messages like this in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.
