### ISSUE TITLE
Kee kills Google OAuth

### ISSUE THREAD

**Issue by constip** [kee-org/browser-addon#216]
Recently I opened [this issue](https://stackoverflow.com/questions/54441075/oauth-signin-not-working-in-firefox-but-chrome) on stackoverflow.

With a bit of testing around I managed to pin down the blame on Kee: The extension seems to somehow block Google OAuth2 to keep logged in. With Kee enabled, the login function just returns without logging in.

The code is from [Subscriptions: List](https://developers.google.com/youtube/v3/docs/subscriptions/list), you can find the whole code by switching to "Full sample".

**Comment by luckyrat** [comment]
Per the [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please search and then post messages like this in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.
