### ISSUE TITLE
Using Kee does not reset workspace lock inactivity timeout

### ISSUE THREAD

**Issue by Socob** [kee-org/browser-addon#218]
As far as I can tell, actively using Kee (having form fields filled in, etc.) does not seem to reset the inactivity timeout that can be configured in KeePass which locks the workspace after a certain time without user interaction (“Tools → Options… → Lock workspace after KeePass inactivity (seconds):”). I’m not sure how difficult this would be on a technical level, but it would be nice if using Kee to fill in form fields also reset the timeout so that the database password does not need to be input again even during active use.

**Comment by luckyrat** [comment]
Per the [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please search and then post messages like this in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.

Would be interesting to see what the rest of the community thinks of the idea, my initial reaction is that it sounds like a good feature to add if technically feasible.
