### ISSUE TITLE
Kee cannot handle REF entries, based on duplicate records.

### ISSUE THREAD

**Issue by Riddim** [kee-org/browser-addon#220]
If a duplicate recoder is made, the username and password can be referenced to the copy. Then another URL can placed to have the same loginname/password. (development reasons).  Kee now copies litterally the reference string ({REF:U@*********). Implementing this would be nice feature maybe?
![image](https://user-images.githubusercontent.com/5503640/53514967-3a274380-3ac9-11e9-8e12-3903f35b4a27.png)

Tested on Browser **Firefox** and OS Windows

**Comment by luckyrat** [comment]
Per the [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please search and then post messages like this in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.
