### ISSUE TITLE
Support for bank special IDs

### ISSUE THREAD

**Issue by FadeMind** [kee-org/browser-addon#221]
Please add to default WHITE list in addon new entries:

Text Field Name:
```
loginInput:nik
```

Text Field ID:
```
input_nik
```

This is valid for `centrum24.pl` LOGIN WIZARD. 
![scr-1551346530-001](https://user-images.githubusercontent.com/9846948/53556684-a5fac200-3b44-11e9-8f55-8e7e8fe4a48f.png)

and please add abilities for EXPORT/IMPORT settings from addon to JSON/XML file for sync settings on another devices.

**Comment by luckyrat** [comment]
Per the [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please search and then post messages like this in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.
