### ISSUE TITLE
Favicon not used any more ?

### ISSUE THREAD

**Issue by dusscloud** [kee-org/browser-addon#222]
I have been using keepass and kee with firefox for some time now.
When looking in Keepass, I noticed that saved entries through kee in the browser does not use the favicon anymore, but use the standard icon (yellow key).
I checked in Kee options, the related option is enabled.

**Comment by luckyrat** [comment]
Per the [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please search and then post messages like this in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.

https://forum.kee.pm/t/keepass-2-4-0-favicons-when-creating-new-passwords-kee-2-3-19-1/1541/2
