### ISSUE TITLE
Request: PGP signed downloads with checksum

### ISSUE THREAD

**Issue by akwala** [kee-org/browser-addon#24]
Since the plugin now needs to be downloaded separately, it would be good to provide PGP signed downloads with checksums.

**Comment by luckyrat** [comment]
I'm not sure how feasible PGP signing would be but I could certainly post some file hashes somewhere if you're concerned about the integrity of GitHub servers... of course, the question then is where - the Kee website is soon going to be somewhat dependant on GitHub so that's not going to get us very far.

**Comment by akwala** [comment]
Is the feasibility of PGP signing questionable due to GitHub's lack of a convenient way to sign downloads? 

Would it be feasible to PGP sign the file containing the hashes?

**Comment by Aetf** [comment]
I think signing the release tag should be enough.
https://help.github.com/articles/signing-commits-using-gpg/

**Comment by luckyrat** [comment]
Since this issue was created I have released Kee on the Firefox add-ons website and published a beta version on the Chrome extension store, both of which apply their own code signatures.

Regarding the pre-release versions on GitHub, these are now generated automatically by TravisCI so you can trace the build that created the files back to a specific GitHub commit via the CI build that created the release. E.g. https://travis-ci.org/kee-org/browser-addon/builds/326184561

I'm not aware of a way that GitHub can attribute a commit to me without the use of either my private SSH key or GitHub login credentials; it is reasonable to assume that if these become compromised, any supplemental code signing I could perform would also be compromised. Therefore I am closing this issue.
