### ISSUE TITLE
Expired entries showing up in HTTP auth window

### ISSUE THREAD

**Issue by elieux** [kee-org/browser-addon#240]
I see this has been discussed on the forum without a push towards a code change.  Recommending people to edit all their expired entries to achieve what I feel is the only reasonable behavior seems user-unfriendly.

The way I see it, expired entries are just like entries in the *Recycle Bin*, they don't work anymore, they are not to be used by Kee.  If there are use cases for filling expired entries (as people on the forum seems to suggest), I recommend creating an option.

If you're okay with this proposal and the "Expires" field is accessible from Kee, I can make a PR for this.

**Comment by luckyrat** [comment]
I don't recall the details of the forum discussion you mention but there is no way to make a change to Kee to support this since it does not have the "Expires" field available to it. Thus any code changes would have to be made in KeePass and Kee Vault initially (and possibly only, depending upon what sort of optional behaviour is implemented and how we wish to configure those options). If you have anything new to add to the forum discussion, please feel free to do so and we can keep it focussed there until such time that we determine what code changes we want to make and to which projects.
