### ISSUE TITLE
Give me an option to use firefox password manager alongside Kee

### ISSUE THREAD

**Issue by Kaan88** [kee-org/browser-addon#242]
I want to use firefox built-in password manager for unimportant stuff, I don't want to login to keepass everytime I want to access my router page. Is it possible to add an option in Kee to not disable built-in manager?

**Comment by sephie** [comment]
Took me way too long to figure out this was my problem too.

**Comment by Magneticdud** [comment]
Apparently it's more user friendly to behave like this. It has been asked 3 years ago in issue #55 but according to user experience experts it's much better to automatically disable the firefox password manager at each start without any warning.

This makes this addon completely unusable (i vastly prefer to copy-paste from keepass rather than this "solution" ), but otherwise looks like the regular people gets confused if there's two password prompts at the same time
