### ISSUE TITLE
[Feature Request] Don't show little icons in textboxes for certain domains

### ISSUE THREAD

**Issue by lonix1** [kee-org/browser-addon#250]
It would be nice to prevent the plugin from filling in forms on certain domains - so it won't show those little icons inside text boxes.

There is a blacklist option, but it is for specific form elements. We need to be able to block the autocompletion and little icons from the entire domain. If we want to use it, we can rely on context menu.

**Comment by lonix1** [comment]
I found a workaround. We can add a custom entry, then tick all the whitelist boxes, but leave them empty.

That tricks the plugin into looking for forms/elements that don't exist, and so the little icons are not rendered, and the form is not mangled on that specific site.

This should be documented as official behavior, or, better, reworked because it's kinda hacky.

**Comment by luckyrat** [comment]
Icons only get inserted when there is a matching entry so it wouldn't make sense to block Kee from working on those domains. Anyway, if you want to provide some more information or contribute to similar discussions, this is what the (community forum)[https://forum.kee.pm] is for, rather than this code issues tracker.
