### ISSUE TITLE
Save last login data not working when window is closed

### ISSUE THREAD

**Issue by Borkason** [kee-org/browser-addon#253]
There are some websites that open a new window for the logon form. When that window gets closed  after logon, the option 'save last login information' is no more available in the Kee addon icon.

The 'save last login information' should be persistent. At least for a short amount of time like 30 seconds.

**Comment by luckyrat** [comment]
If it's a different domain, we can't do anything since it would be unsafe to associated the data from the popup window with the tab in the main window. If it's the same domain, perhaps we can add some new feature to address this situation but I think it is a logon approach that is becoming less common so we may not prioritise it. Please feel free to open a discussion on the community forum with more information about how we can find examples of this and how any proposed change to Kee behaviour would fit alongside the updated user interface in version 3.5.

https://forum.kee.pm
