### ISSUE TITLE
Support for JS login form with <button> submit

### ISSUE THREAD

**Issue by Yamakaky** [kee-org/browser-addon#256]
An internal business app I use doesn't work with the Kee browser extension + Keepass. It uses Vue.js and the login form can be simplified to:
```html
<form>
  <input type=text placeholde=Login></input>
  <input type=password placeholde=Password></input>
  <button type=button>Login</button>
</form>
```
When I manually fill the form, Enter doesn't work, I have to manually click on the Login button.
(this behavior is actually quite annoying to use, but it won't be fixed anytime soon...)
When I use Kee, the autocomplete works correctly, but the autosubmit only reloads the page since the app doesn't listen to the submit event for the form.

Not sure what could be done to make Kee work, apart from sending the click event to the button. I assume Kee sends a submit event by default? It could be configured in the site specific section.

**Comment by luckyrat** [comment]
Kee should already work fine with button submit methods; we only fall back to using the submit event if we have no other choice. Perhaps there is something else going on with this specific site. Anyway, if you want to provide some more information or contribute to similar discussions, this is what the (community forum)[https://forum.kee.pm] is for, rather than this code issues tracker.
