### ISSUE TITLE
Extension removes Chrome native 'suggest password' option

### ISSUE THREAD

**Issue by alystair** [kee-org/browser-addon#259]
Kee's built-in password generator is not as strong as Chrome's - getting declined at a few services. I'd like to use Chrome's native 'suggest password' option instead but your extension removed it... Please either re-add it or add an option to do so.

**Comment by Xeevis** [comment]
Kee doesn't implement a password generator, KeePass2 does and you can customize it any way you like using patterns. https://keepass.info/help/base/pwgenerator.html

**Comment by luckyrat** [comment]
I don't think there's any way to control Chrome's behaviour to this level of detail and as @Xeevis points out, using and, if necessary, improving the password generation process within Kee is how we should proceed. Anyway, if you want to provide some more information or contribute to similar discussions, this is what the [community forum](https://forum.kee.pm) is for, rather than this code issues tracker.
