### ISSUE TITLE
Sending HTTPAUTH doesn't work on Firefox Beta

### ISSUE THREAD

**Issue by artgru** [kee-org/browser-addon#265]
Problem appeared in one of the last iterations of Firefox beta. I am currently on 78.0b9.
If the page is protected with a htaccess, Kee opens a popup (like usual) with an option to select a proper user credentials.
But when I click it, window just reappears again and credentials aren't sent.

Sadly I cannot open my profile in the release version of Firefox due to some significant changes, but in my older profile everything works flawlessly. So beta branch brought something new in the auth process which probably needs to be addressed by Kee.

**Comment by luckyrat** [comment]
It looks like this was a bug in the new Kee beta rather than anything to do with a Firefox update. I've pushed out a quick fix so when your browser downloads the latest version (3.4.5) it should start working again. Thanks for reporting the problem. Please let me know if the new version fixes the issue or not.

**Comment by artgru** [comment]
Sorry for the late response, yep it's fixed ;)
