### ISSUE TITLE
Kee Bowser-Addon popup displays only 16x16 pixel low resolution favicons.

### ISSUE THREAD

**Issue by Marrib** [kee-org/browser-addon#270]
**Current situation**
The redesigned interface of the Kee Plugin version 3.5 is great, I really enjoy using it.

When searching inside the Kee plugin popup, the search results are displayed with a low resolution favicon of 16x16 pixels which is scaled up to 32x32 px resolution and therefore looks very low quality. This happens despite the fact that all my favicons stored in the KeePass database have a native resolution of 32x32 px. That means somewhere in the communication chain between KeePass and the Kee plugin the 32x32 px favicons from the KeePass database become scaled down to 16x16 in the first step and then the Kee plugin scales them up again to 32x32 px resulting in a very low quality look. 

**Change proposal**
Please change the Kee plugin so that it displays the 32x32 px favicons without quality reduction.

**Configuration information**
OS: Windows 10 Pro x64 1909
Browser: Firefox 79.0 x64
KeePass: 2.45 x64
KeePassRPC: 1.12.1
Kee Browser Plugin: 3.5.19

**Comment by luckyrat** [comment]
Thanks for the feedback. I agree that this would be a nice improvement and it's already on my wish list.

Kee is already capable of handling higher resolution icons though - it's KeePassRPC and Kee Vault which need to be updated. This requires a complete re-write of the way we deal with icons because the current approach from 2010 is not efficient enough to cope with today's larger icon sizes.

Since there's nothing to be done in Kee to enable this, I'll close the issue now but rest assured I won't forget about it - it's just a question of when I will be able to find the time for such a large piece of work. Since custom icons in Kee Vault are already supported and it is much easier for me to make changes there than in KeePassRPC, I'll probably enable the improvement for Kee Vault first and take what we learn over to KeePassRPC later.

**Comment by Marrib** [comment]
Thank you!
