### ISSUE TITLE
Kee box-shadow interferes with :focus styling

### ISSUE THREAD

**Issue by sekra24** [kee-org/browser-addon#325]
I recently noticed that the kee css style "box-shadow: initial !important;" has an major impact on a lot of css frameworks like tailwind or bootstrap and their styling for focused input fields. 

In this case kee browser-addon overwrides the :focus state with it's "box-shadow: initial !important;" like in this example.

Kee browser addon active:
<img width="348" alt="kee-active" src="https://user-images.githubusercontent.com/11167542/217108876-4662bbf4-0039-4a59-a6c9-0942c05cf60f.png">

Kee browser addon NOT active:
<img width="335" alt="kee-not-active" src="https://user-images.githubusercontent.com/11167542/217108882-4fb00545-063a-4c29-a182-e5577e93e30d.png">

As you can see the focus state is completely ignored because of the box-shadow: initial !important; which is added by kee browser-addon.

Is it nessesarry to have this css style overwriting every box-shadow styling? 

Thank you.

Best, Sekra24

**Comment by luckyrat** [comment]
Yeah it's needed to make some pages work correctly - see PR #226

This is the first time I've heard of it causing a problem though. At least it appears to be only a cosmetic issue so it's best that we keep the existing behaviour since reverting that change would cause the Kee icon to no longer appear at all on some pages.

By the way, in future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just updated to the latest GitHub issue template system to try to make that clearer before one takes the time to write up an issue here).
