### ISSUE TITLE
Feature Request: Fill in one-time passwords

### ISSUE THREAD

**Issue by b4st1en** [kee-org/browser-addon#330]
Most sites now offer the option of using an OTP, and KeePass has been managing them for a while now.

So we spend our time using two tools... Kee for the login and password, but also KeePass to get the corresponding OTP..

Therefore the use of a plugin is no longer worthwhile.

Do you plan to manage OTPs in Kee? And when?

**Comment by luckyrat** [comment]
These sorts of discussions are best had on the community forum but in brief, no specific plans because it's not clear what OTP management would benefit users but it's something we'll give more thought to as and when use cases are identified and discussed.

By the way, in future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just updated to the latest GitHub issue template system to try to make that clearer before one takes the time to write up an issue here).
