### ISSUE TITLE
Kee does not offer anymore to safe a new login

### ISSUE THREAD

**Issue by HyperCriSiS** [kee-org/browser-addon#331]
Hi,

since a while Kee does not offer anymore to safe a new login.
Normally after a new login the + was flashing and I could add the new credentials.

Also I have a strange bug with the DB that is actually loaded. 
Sometimes it show the last Backup of the DB as name. 
![cdqDAPnbwj](https://github.com/kee-org/browser-addon/assets/11708192/db7cf065-c363-40dc-b619-0034d9dd2980)
When I click "open Keepass" the DB name is corrected.
![OoyEMXu19Y](https://github.com/kee-org/browser-addon/assets/11708192/9097fe7c-df88-470e-81dd-8d4ebfa5b787)
Always when this happens I also do not get login suggestions, until I klicked "open Keepass".

Best regards
Hyper

**Comment by luckyrat** [comment]
Probably some backup plugin is messing around with your KeePass files but we'd need a lot more information about how to reproduce this before we can offer any targetted help. It's likely that the issue is nothing to do with Kee so maybe take a look for similar problems with backup files on the KeePass support forum first but if you're still stuck and can provide some more details, please create an issue on the Kee [community forum](https://forum.kee.pm/).

By the way, in future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just updated to the latest GitHub issue template system to try to make that clearer before one takes the time to write up an issue here).
