### ISSUE TITLE
Support KP2A_URL_* string fields from keepass2android for multiple URLs per KeePass entry

### ISSUE THREAD

**Issue by wschlich** [kee-org/browser-addon#334]
The Android app keepass2android (https://github.com/PhilippC/keepass2android) supports adding additional URLs per KeePass entry (instead of duplicating entries and using references for username and password, for example) by adding string fields with a name in the form `KP2A_URL_1`, `..._2`, `..._3` and so on. This is quite nice and I'm using this a lot (for storing android app URLs like `androidapp://com.zdf.android.mediathek` in addition to the regular web site URLs like `https://www.zdf.de`, but also for adding secondary website URLs like some special SSO URLs, where the latter is the reason I opened up this issue.
Would you please consider supporting these additional URL string fields, at least in the Kee browser extension?
Thank you!

**Comment by raleik-pl** [comment]
I totally second this! I'm surprised there is so low feedback on this. It's really a must-have! For instance Microsoft services use live.com, microsoftonline.com, office.com etc.

**Comment by luckyrat** [comment]
Just so everyone is clear, Kee has always supported multiple URLs per KeePass entry. Just add them to the URLs tab in the Kee section of the KeePass Entry editor or the browser integration/settings section of a Kee Vault entry.

I don't plan to implement support for understanding the various similar features of other plugins and ports but for sufficiently popular and stable 3rd parties (this Android port would be one in my opinion) I would accept a PR that optionally appends any such URLs to the list Kee already has. That PR would not belong in this repository but rather https://github.com/kee-org/keepassrpc/ and/or https://github.com/kee-org/kprpc (although the latter may be superseded by a Flutter equivalent in the coming years so bear that in mind if targetting Kee Vault).

Therefore I am closing this issue since it's not something that would be implemented in the browser extension.
