### ISSUE TITLE
Support new Firefox international domain name representation (punycode)

### ISSUE THREAD

**Issue by NodokaMurmevent** [kee-org/browser-addon#36]
hello thanks for all you wok on webext to keefox.

i have a client with a internationalized domain name and keefox not propose login & password 
https://en.wikipedia.org/wiki/Internationalized_domain_name

i don't know if it a problem with keepass or the browser ext who can i provide you more information ?

**Comment by luckyrat** [comment]
Hi,

It is most likely this would be an issue with Kee rather than KeePassRPC so you can provide information here and I'll create a ticket in the keepassrpc project if necessary.

Can you say which URL in particular is causing trouble?

Have you tried creating a new KeePass entry using Kee's "save login" feature?

**Comment by NodokaMurmevent** [comment]
i have try with alapha13 and the problem is always here.
i have also tested the domaine name with the old keepass and firefox56 it's work perfectly.

On this domain keepass are not prompted with the "translated" domaine name
domain tested : 
translated : [edenbeauté.fr](https://edenbeauté.fr/wp-login.php)
international : [xn--edenbeaut-j4a.fr](https://xn--edenbeaut-j4a.fr/wp-login.php)
(take care if you try too many failed login you will be blacklisted)
in my keepass DB if i save the password with edenbeauté.fr it's not work but if it's with xn--edenbeaut-j4a.fr it's work. Problem, by default keepass create the entry with the translated domain name.

> Have you tried creating a new KeePass entry using Kee's "save login" feature?

in my firefox58 kee never prompt me for save any password y save all manually i don't no why but he propose me the saved entry without any problem.

**Comment by luckyrat** [comment]
Thanks for reporting the problem.

This is actually unrelated to Kee or KeeFox but rather a change which Mozilla have made to Firefox 57: https://bugzilla.mozilla.org/show_bug.cgi?id=1380617

We will need to consider:

1. How can we support both old and new formats of URI?
2. Is there any security risk if we do/don't take action before releasing Kee 2.0?
3. Is this another potential reason to force us into a flag-day switch over from KeeFox to Kee on the day Firefox 57 is released?
4. Impact on Chrome support? (probably none since FF bug says "In terms of web-compat these changes make us match the behaviour as all other UAs.")
5. Is there, or will there soon be, a WebExtensions or Web API to enable safe conversion to/from these alternative formats?

https://bugzilla.mozilla.org/show_bug.cgi?id=1400023 is highly relevant - the built-in Firefox password manager has had to be modified yesterday to support this format change.

**Comment by luckyrat** [comment]
Kee already bundles a punycode library as a dependency of the public suffix list domain identification library.

Therefore fixing this should be a relatively straightforward synchronous call to `punycode.toUnicode(input)` from one or more code locations but we should consider the above points first:

1) `punycode.toUnicode(input)` claims to treat inputs that are already unicode transparently so calling this in FF56 should not affect the behaviour in that version.
2) If we don't include this in Kee, users of FF57+ could find that KeePass entries with the punycode alternative URL begin to be filled into a website where previously this did not happen. While potentially confusing, there may have been an expectation that this would have worked in the first place so the risk doesn't extend beyond a very minor privacy change; there's no security risk.
If we do include this change in Kee, users of alpha versions of Kee that have saved entries with internationalised domains will find that these entries do not match any more. Again, an easily fixed annoyance but not a security risk.
3) No
4) None (given the solution is insensitive to whether the input is Unicode or Punycode).
5) Since we're already bundling the code needed to do this, there's no benefit in even considering a dependency on some future API

**Comment by luckyrat** [comment]
This should be fixed in alpha 18: https://github.com/kee-org/browser-addon/releases/tag/2.0.0-a18

(and alpha 17 for what it's worth)

**Comment by luckyrat** [comment]
I'll assume this is fixed unless I hear of problems over the next week but will track for the 2.0 release just in case.

**Comment by luckyrat** [comment]
Appears to be fixed as expected.
