### ISSUE TITLE
Site not working

### ISSUE THREAD

**Issue by Dschayem** [kee-org/browser-addon#61]
Kee doesn't recognize the site https://www.deka.de/privatkunden
The username and password field is on the right. In KeeFox, it works.

**Comment by luckyrat** [comment]
Please can you try it in Beta 6: https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/2.0.0.24b6

**Comment by Dschayem** [comment]
No sorry, can't get it to work.
Sometimes it finds matching log-ins when i press the option in the menu, but it can't auto-fill it. If i put in manually, it doesn't ask for saving the entry. It seems it finds the correct entry, but can't regonize the form-fields.

**Comment by luckyrat** [comment]
Hi,

If you click "Depotzugang" at the top you see the actual log-in form which Kee fills in. It seems to work fine for me, although I have no valid credentials to perform a thorough test with.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable.

Thanks,
Chris
