### ISSUE TITLE
Support for N26

### ISSUE THREAD

**Issue by marcelkorpel** [kee-org/browser-addon#62]
When browsing to https://my.n26.com the email and password fields are not filled, although a matching set is present in KeePass. Right-clicking one of those fields, chosing 'Kee >' and selecting the correct entry results in a password showing up in the password field, but the email address is not inserted. In both fields the Kee logo appears, but the popup shown after clicking on it doesn't reveal a matching login.

To reproduce, insert a random username and password in KeePass for the mentioned URL and navigate to that page.

Also note that KeeFox 1.x wasn't able to fill these fields correctly, too.

**Comment by luckyrat** [comment]
It seems to work for me in Beta 5 - https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/2.0.0.23b5

I think it probably didn't, or was at least intermittent in earlier beta versions.

Note that auto-fill is disabled because the form isn't clearly structured enough for Kee to have high confidence that it should insert data into it - clicking the Kee icon and selecting the matched login works for me though.
