### ISSUE TITLE
Search all logins

### ISSUE THREAD

**Issue by luckyrat** [kee-org/browser-addon#7]
Needs to be re-implemented since old technology that enabled this feature is no longer available in Firefox.

**Comment by luckyrat** [comment]
Not sure what the use cases are for this if we can't get a one-click login to work anyway so may not tackle this until next year. Happy to discuss a spec and help someone else implement it in the mean time though.

**Comment by 01i** [comment]
I was just reading through the Kee 2.0 features thread which links here and wanted to point out a couple of examples of how I've found searching to be useful. For the most part, it's been when developing WordPress websites.

The first scenario (and most common) is when adding the license for a premium plugin. Sometimes the authentication method asks for username and(or) password from the plugin providers website. 

The second is when restoring a development site to a live site using a new url. It's handy to be able to pull the user details from the old URL.

In both cases it would be easy enough to get the information directly out of KeePass, but search combined with the copy password option is quicker. I only ever really use search in combination with the copy password to clipboard option.

**Comment by freaksterrao** [comment]
I use KeeFox search to navigate to a site and login. I dont have most sites bookmarked as KeePass has the URl and KeeFox allows me to search for the site and open it.

Navigating sites will be a lot harder for me once I start using Kee because I am so dependent on the Search feature.

**Comment by luckyrat** [comment]
Thanks for commenting @01i and @freaksterrao 

It's interesting to hear of two different use cases for the current functionality. In @01i's case it sounds like searching in KeePass is the best workaround at the moment but for @freaksterrao searching in Firefox would be better, although that obviously depends upon the URIs first being stored within Firefox. 

One thing you might want to try is the export bookmarks feature in KeePass. Go to File > Export and select the Mozilla Bookmarks HTML file format.

Save the export file somewhere and then import into a folder within Firefox:

1. Load the Library (ctrl-shift-B)
2. Import Bookmarks from file
3. Select the file you exported earlier
4. Once that's imported, you should see all the new bookmarks listed in a new folder at the bottom of the "Bookmarks Menu" folder.
5. You can then organise the bookmarks into different folders or put some on the bookmarks toolbar if you want.
6. You should now be able to easily search for the site you want by typing your search term in the Firefox address bar
7. tip: you might want to put the * (star) character in the search query too since that filters the search to only bookmarks (rather than history, etc.)

**Comment by tgp1994** [comment]
This is also a feature I just found myself looking for. I use it on and off for various purposes, normally when a website isn't properly detected so I can update the appropriate login.

**Comment by oxygen-gb** [comment]
Really would like search to be implemented again.

We have lots of  our customers on hosted exchange email with various vendors
We save the logins for each customer to KeePass and we use(d) the search in KeeFox to look for the customer we want rather than having to know which vendor's website to use and then scroll through a long list of customers until we find the right one.

Our usage is somewhat similar to what O1i said

**Comment by ntnsndr** [comment]
Agreed that this is a crucial and much-missed feature. It would be great to see it come back in some form, better than ever. I used the search frequently, both for bookmarks and to locate passwords that didn't necessary match the page I was presently on.

Thanks to @luckyrat and all other contributors to this important project.

**Comment by Asimov500** [comment]
I was annoyed at first, but after luckyrat explained the situation with firefox I understand, but I am annoyed about the features removed. I do have a question though. On my computer at work before I shut down firefox and restarted it the old keefox was still working in the upgraded firefox. Is there anyway for us to install the old keefox  instead of the new one, until the search features are added to the new one? I have been using keefox as a bookmark program for years now, so I was wondering.

**Comment by dlech** [comment]
To use KeeFox 1.x, you need Firefox < 57. If you want a supported version of Firefox < 57 (e.g. for security updates), you can try Firefox 52 ESR <https://www.mozilla.org/en-US/firefox/organizations/faq/>.

**Comment by MathiasRenner** [comment]
Thanks @dlech for the quick fix suggestion. 

Most of the users I know incl. myself follow the use case described by @freaksterrao: No bookmarks for any login site - just using KeeFox search.

So I really hope that the search comes again soon.

**Comment by Asimov500** [comment]
The workaround for exporting bookmarks although works is a little bit of pain. It's ok to use this method once but  I am constantly adding a new url to keepass and having it show up in the browser in keefox. Otherwise you end up having to add urls twice. Once in keepass and again in Mozilla.

Is keefox open source? and is it written in c++ or c#?

**Comment by luckyrat** [comment]
Kee is open source and welcomes contributions (pull requests). This issue tracker is directly associated with all the source code. The relevant part for search would be written TypeScript - indeed, much of the underlying functionality has been written already in order to support searching for logins when updating an entry.

I'll try to find some time at the weekend to gather everyone's feedback into a coherent specification for a new search feature and we can see where to go from there.

My main concern now is the poor support from Firefox for persistent/overlay panels. None of the solutions I've tried and included in Kee so far really allow for a great user experience but that may be resolvable somehow.

**Comment by Asimov500** [comment]
I suppose we could all write nasty letters to Mozilla threatening to install chrome unless they give you the supreme power of the api, is out of the question then?

**Comment by slovdahl** [comment]
Thanks for a great plugin and for taking the time to look into this issue @luckyrat. The search feature was in my opionion the feature that made KeeFox stand out among other KeePass plugins, it really made it awesome to use.

**Comment by miblo69** [comment]
I second  @slovdahl et al who appraise the plugin. It is a great help and makes things easier but I really miss the feature of searching the database within Kee/Firefox. 

As an example, I needed to login to make this comment. Kee did not detect the GitHub login URI, so normally I would just search in Kee. But not today... Search in KeePass instead, and copy-paste username, copy-paste PW. A bit more combersome than in the previous version.

@luckyrat Thanks for the great work so far. Would be much appreciated if the search could be added back again.

**Comment by te-deum** [comment]
Hello,

The same here... Great plugin but the search is the key function that made KeeFox the best KeePass plugin for Firefox...

Thank you for your work and I hope to see the search back soon.

**Comment by Drraze** [comment]
Searching for logins was the best feature KeeFox had over any competition. One of the main factors that kept me using Firefox. Right clicking to copy names and password for the numerous sites that don't work with the automatic credential entry saved so much time. Prime example would be Github itself, where I had to go into Keepass database and find the credentials, since Kee wasn't picking up the fields.
Really hope this feature comes back, since now Kee is the same as every other password manager.

**Comment by luckyrat** [comment]
> Right clicking to copy names and password for the numerous sites that don't work with the automatic credential entry saved so much time. Prime example would be Github itself

Well hopefully the improved form filling will reduce the pain somewhat until we can come up with a replacement search feature. For example, login to GitHub works just fine now.

> Did I understand it correctly, automatic fill and login triggered from a click in a search result is not possible any more?

Certainly not implemented at the moment and it will be much harder at the very least, potentially not possible but I wouldn't know for sure until spending a lot more time looking into it.

It increasingly seems that the main use case is searching in a bookmark fashion and being able to get access to the KeePass entry, copy passwords, etc. so that's what I intend to focus on first.

**Comment by Asimov500** [comment]
I write web apps, and people almost never use the software as it was intentionally made. You have one idea eg filling in passwords and others have their own ideas. I have been using keefox and keepass for years as a replacement for the firefox bookmarks. Since keefox lost this feature I have now been going through all my old bookmarks in firefox that I had even forgotten were there LOL.

**Comment by McEnnes** [comment]
I have a lot of logins available in Keefox which i use on a daily basis.
The logins are organized in different categories like e-mail, work, web shops etc 
The Keepass database is synchronized by way of my Synology Nas and cloud station software on various PC,s and laptops.
Exporting and working with bookmarks is not an option for me, so using Kee is not an option right now.
For now i will keep using the latest Keefox version until this issue is solved, winch will hopefully happen!

**Comment by OrYaYo** [comment]
I agree with the above comments: Searching for logins and being able to directly login (or being redirected to the login page) of stored sites was the feature that made Kee(Fox) stand out from other keepass plugins - No doubt. 

As many other users say here, I have downgraded Firefox to version 56.0.2 and installed KeeFox 1.7.2 until this feature is implemented again. In fact, the main point I use Firefox and not Chrome is because this feature on Kee (not available in other Chrome plugins such as ChromeIPass). 

In case you are wondering what I did: 


1. Download Firefox 56.0.2 (There are links to this version here: https://support.mozilla.org/en-US/kb/install-older-version-of-firefox or directly from the old version page: https://ftp.mozilla.org/pub/firefox/releases/)  

2. Install KeeFox 1.7.2 (Here: https://addons.mozilla.org/es/firefox/addon/keefox/versions/)
Disable automatic Firefox Updates (type in about:preferences in the browser URL field and go to Firefox Updates to disable updates)

3. Disable automatic add-on updates (type in about:config in the browser URL field, look for extensions.update.enabled and double click it to disable the automatic updates for add-ons). 

A dramatic decision, but I cannot continue to use Kee, nor Firefox, without this feature and I will keep on using and old version of Firefox until this is re-implemented. Hope this feature is coming out soon back again!

**Comment by mberger-git** [comment]
Hi,
I agree to OrYaYo, the search feature within the logins is the main reason why I use Firefox instead of Chrome. I would really appreciate to see it in Kee again!
Thanks for the great extension!
Mathias

**Comment by mygithuber** [comment]
Maybe this helps calling external programs (like KeePass) from inside Firefox-57:

Same problem with FDM (Free Download Manager). Its [AddOn](https://addons.mozilla.org/de/firefox/addon/download-with-fdm/) uses a helper called '[native client](https://github.com/belaviyo/native-client/releases)' with node.exe for starting FDM...

https://add0n.com/download-with.html?from=fdm 
https://www.freedownloadmanager.org/

**Comment by alexmarketaccess** [comment]
Really, really, really miss searching from browser! That feature saved me so much time!

**Comment by eraguzin** [comment]
I just also want to say I really really miss this feature.  I've tried to live without it for a month, but it sucks.  If there's not a fix soon, I'm going to switch over to something else.  In part, it did replace bookmarks for me.  It also helped when I had multiple logins to a single website.  I could search the website, and with one click sign in with the login I wanted.  This feature was **essential** overall.

**Comment by HyperCriSiS** [comment]
The Login selection within the browser was by far my most used feature!
KeePass is not the same without it :( I do not want to organize all those sites in the Bookmarks.
Thats really unpractical.
Would LOVE to see this feature back, PLEASE! :)

**Comment by schlaubstar** [comment]
I would like to join with the previous speakers in saying that the search function has made KeeFox the best extension for using KeePass in Firefox. The solutions described here with bookmarks can only be seen as temporary workaround but the Search Function is essential to have all things in one common place. I currently also switches to the old Firefox ESL Version, although I like the new look and especially the performance of Quantum, just because Kee seems to be unusable to me.

**Comment by huehnerlady** [comment]
@OrYaYo Thank you so much I will do the same now I think

**Comment by luckyrat** [comment]
#143 will add a new search feature to the Kee button popup in February. #145 means that the usability is somewhat compromised in Firefox but it works well in Chrome and on the plus side, the relevant Firefox bug does seem to be getting a little bit of attention from the Firefox devs so will hopefully get fixed this year.

I don't intend to replicate the full list of grouped logins that some people might have used for similar reasons to the search feature but if it turns out that the search functionality is insufficient for your use case, I'm happy to discuss further on the forum and potentially offer help for someone else to develop the feature if it can be shown to have no negative impacts.

**Comment by giftfish** [comment]
Yeah, I have to agree with everyone here.

The removal of this functionality is a significant drawback. Being able to directly navigate to the URL via the dropdown was an enormous timesaver and very important to my workflow. 

For any site where I *knew* I'd have to log in, I'd access that site via the Keefox menu. Since the URL was accessible there, that also meant I didn't need to create a separate bookmark, which was convenient. The ability to show groups ensured all similar sites were located together, which kept things organized and also allowed for very rapid navigation between sites. It took a maximum of three clicks and a moment to log into a site (Plugin icon > site > log in) -- two if you enabled the auto login feature. 

Now, the amount of time/clicks it takes depends on how deeply the bookmark for the site happens to be buried in my organizational scheme. I tend to create a couple of levels of folders/subfolders since I have a lot of bookmarks. Separators just doesn't always cut it. All of this means it takes much longer to click/hover/scroll and navigate to the proper bookmark. It also makes switching between sites much, much slower.

---

As a side note, it now *always* takes 3 clicks -- with a separate dialog box to boot -- and a few moments to log into a single site. Plugin icon > Matched entries > log in. This wastes time. Why not show the matching entries *immediately* when clicking on the plugin? After all, this is what the user will want to access a majority of the time.

**Comment by luckyrat** [comment]
The 2.2 beta enables this feature.

If you're a new beta tester, please use https://github.com/kee-org/browser-addon/releases/latest if you're installing on Firefox or https://chrome.google.com/webstore/detail/kee/mmhlniccooihdimnnjhamobppdhaolme if Chrome.

Existing beta testers will receive an update in the next day or so.

**Comment by McEnnes** [comment]
i might be doing something wrong, but this does not seem to enable this feature!
I can see and use the login for the web page i am on, but i do not see a list with all the logins!

**Comment by mygithuber** [comment]
In version 2.2 beta the is a search field only, NOT the fromerly known (v1.7x) list of all the logins...

So character input work with searching the known logins must be done. 
The old folding menu with known logins is missed painfully!

Regards!

**Comment by McEnnes** [comment]
This issue was closed, but why? 
The 2.2 beta enables this feature is not true unfortunately.
What we can do is use keefox 1.7.2. in combination with waterfox.

**Comment by Asimov500** [comment]
I have just tried the new 2.2.
I will start by saying the new search function is wonderful. It now means I won't have to keep going back and forth to keepass now, which was my main bug bear.

However I miss the old drop down menu, where I had stuff organised under different headings in keepass.
I will say just adding the Search bar has improved the situation though.

If you could put the old drop down menu back then Kee will be as good as Keefox.
Could we add the fox back to kee LOL. I liked the old name 'cause foxes are cool.

Thanks.

**Comment by ntnsndr** [comment]
I love it! Thank you so much @luckyrat!

**Comment by schlaubstar** [comment]
@McEnnes Have you installed the latest beta ? I do not really know where your problem is.
Take a look at my screenshot: At the TOP I typed in "WEB" and then, as a result, I get the long missed list with matching entries and even Icons ... So I myself will switch to Quantum now, as this was the most essential missing feature (for me).

![2018-03-06 22_16_12-](https://user-images.githubusercontent.com/25862995/37058968-6379d8e4-218c-11e8-92f6-61d4d7e7e483.png)

@luckyrat :+1:  Thank you so much for bringing back this feature to live !

**Comment by McEnnes** [comment]
I did see that and it is a big improvement.
I am still missing the option to make groups, that makes a better oversight when you have lots of logins.

**Comment by Vodochnik** [comment]
I miss the old folding menu with known logins too. Yes, i could create many bookmarks, but still...
