### ISSUE TITLE
Delete per-site config entries

### ISSUE THREAD

**Issue by skibbipl** [kee-org/browser-addon#76]
Firefox: 58.0a1 (2017-11-11) (64 bits)
Kee: 2.0.0.21b3

I don't see any way to delete per-site config created in Kee settings. It is possible to do it somehow?

**Comment by luckyrat** [comment]
It's not possible at the moment. It's also not really necessary since you can just uncheck all the checkboxes on the page and set the password saving option to "same setting as all websites" in order to achieve the same effect.

It would be nice to have a way to tidy up old entries from an aesthetic perspective though so I'd accept a pull request that enables this functionality.
