### ISSUE TITLE
See all website-specific settings

### ISSUE THREAD

**Issue by frankhalligan** [kee-org/browser-addon#93]
Not really sure if this is a bug, feature request, or support request. In Kee 2.0, is it possible to see a list of sites for which non-default settings have been set? If I go to options and select the "A specific website" option, all I get is a search box. If I enter a site and customise a setting, I have no way of finding that customisation again unless I remember that I've done it

**Comment by luckyrat** [comment]
It's not possible at the moment.

Two options to consider:

1. Display all results in the search dropdown interface, rather than waiting for 2 characters to be typed. Would have to limit result quantity if we go down that route and potentially restructure the page styles to allow that dropdown to be vertically scrollable.
2. A separate interface to list all items - presumably accessed via the current search interface.

I'm open to other design suggestions.

**Comment by frankhalligan** [comment]
Option 2 would (IMO) be preferable. To minimise changes, I was thinking a simple list/table below the search box listing all current sites with customised settings. Clicking one of them has the same effect as clicking a dropdown result: populates the search box and opens the site-specific settings
