### ISSUE TITLE
Give simple instruction on the plugin welcome page

### ISSUE THREAD

**Issue by gagarine** [kee-org/browser-addon#95]
After installing the plugin you get this "welcome page"

![screen shot 2017-11-19 at 15 24 50](https://user-images.githubusercontent.com/164074/32991551-e2333462-cd3d-11e7-82e2-80b148ebe37d.png)

The text is very long and not structured, and at the end you still need to go to a forum to read again instruction to install...

Also instructions should be platform specific.

**Comment by luckyrat** [comment]
To keep this initial page simple, I moved the majority of the information to the forum. The instructions should already contain instructions specific to each platform.

Can you supply a suggestion of how it should be restructured and shortened?

**Comment by luckyrat** [comment]
Hi,

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable.

Thanks,
Chris
