### ISSUE TITLE
CTA to unlock KeePass from the Kee main panel

### ISSUE THREAD

**Issue by tleepa** [kee-org/browser-addon#99]
At this moment, if the KeePass database is locked, the icon in the browser says "OFF" and I have to go to KeePas, unlock the database and then Kee can fill the login forms.

Is there a way to unlcok KeePass database from the browser?
Some additional action on the toolbar icon/context menu?

PS. I am using Fx nightly:  Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

**Comment by luckyrat** [comment]
ctrl+shift+2 works. Probably worth us adding a button to the main popup menu panel though.

Need a new string: "Login to password database".

Easiest approach is probably to add a new item to the menu list in the panel but I'm open to discussing alternative designs that might pull this call to action closer to the information section displayed at the top of the panel.

Needs to be enabled when the "OFF" label is orange.

Need to check what happens when there is no locked database and no record of most recently used database within Kee - I'm not too fussed whether it triggers an open dialog in KeePass or uses KeePass' own idea of recently used database but I think it should do something.

**Comment by tleepa** [comment]
I don't know why, but Ctrl+Shift+F2 is not working in my browser...

**Comment by rjt** [comment]
CTRL+ALT+K  Will bring the main keepass app to the foreground.

**Comment by luckyrat** [comment]
This will be supported in Kee v3.1.

There are three states for the password manager to be in from Kee's perspective:

1) Not connected
2) Connected but no open databases
3) Connected with open databases

Kee Vault is tightly integrated to the web browser and thus can support an open/unlock button in all 3 states. For the time being the Kee Vault tab will remain focussed after the button is clicked in any state. Eventually we'll aim to detect a successful sign-in/unlock operation and automatically return focus to the tab that was active when the button was clicked.

For KeePass, the existing functionality in KeePassRPC can only support (2). A forthcoming version of the plugin will add support for (3). (1) might not be possible but if there is a way, it will depend upon #23 being implemented first. Focus will remain with KeePass for (3) and return to the browser for (2) and (1), although this behaviour can't be guaranteed on all devices and may change as devices get updated, etc.
